name: Build and Deploy to GitHub Pages

permissions:
  contents: write
  
on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22  # Ensure this matches your project's Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages  # Change this if you prefer a different branch
